version: "3.4"
services:
  app:
    build:
      args:
        user: docker
        uid: 1000
      context: ./docker/php-fpm
    image: travellist
    container_name: admin-panel_app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www

  nginx:
    image: nginx:1.17-alpine
    container_name: admin-panel_nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker/configs/nginx:/etc/nginx/conf.d

  db:
    image: mysql:5.7
    container_name: admin-panel_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker/data/db:/var/lib/mysql

  pma:
    image: phpmyadmin/phpmyadmin
    container_name: admin-panel_pma
    links:
      - db
    ports:
      - "8765:80"
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
